export const enum Command {
  INIT = 'INIT',
  CHANGE_TEXT = 'CHANGE_TEXT',
  SUMBIT_TEXT = 'SUBMIT_TEXT',
  TOGGLE_ALL = 'TOGGLE_ALL',
  TOGGLE = 'TOGGLE',
  CHANGE_FILTER = 'CHANGE_FILTER',
  DESTROY = 'DESTROY',
  CLEAN_COMPLETED = 'CLEAN_COMPLETED'
}
